import { NextRequest, NextResponse } from 'next/server';
import { agentGraph } from '@/ai/graph';
import { HumanMessage } from '@langchain/core/messages';

export async function POST(req: NextRequest) {
  try {
    const body = await req.json();
    const { income, gestation, support, region } = body;

    const query = `I am a parent in ${region || 'New Zealand'}. 
My household income is ${income || 'unknown'}. 
My baby was born at ${gestation || 'unknown'} weeks gestation. 
Currently I am receiving: ${support || 'nothing'}. 
Please evaluate my eligibility for financial grants such as Best Start, WINZ, or Disability Allowance.`;

    const result = await agentGraph.invoke(
      {
        query,
        consentGiven: true,
        intent: 'EXECUTION',
        currentAgent: 'funding_eligibility_checker',
        messages: [new HumanMessage(query)],
      },
      {
        configurable: { thread_id: `financial_eval_${Date.now()}` },
      }
    );

    return NextResponse.json({ 
      success: true, 
      report: result.finalResponse,
      sources: result.sources || []
    });

  } catch (error: any) {
    console.error('API Route Error:', error);
    
    // If we hit the interrupt due to human review (which funding_eligibility_checker requires)
    if (error && (error.name === 'Interrupt' || error.name === 'GraphInterrupt')) {
      const interruptValue = error.value || error.interrupt || {};
      return NextResponse.json({ 
        success: true, 
        report: interruptValue.proposedResponse,
        note: 'This report was generated by AI and is pending human review by a financial counselor.'
      });
    }

    return NextResponse.json({ error: 'Internal Server Error' }, { status: 500 });
  }
}
