import { NextRequest, NextResponse } from 'next/server';
import { agentGraph } from '@/ai/graph';
import { HumanMessage } from '@langchain/core/messages';
import { requireAuth } from '@/lib/api-auth';
import { RateLimiter } from '@/lib/rate-limit';

const limiter = new RateLimiter(60_000, 10);

export async function POST(req: NextRequest) {
  const auth = await requireAuth(req);
  if (auth instanceof NextResponse) return auth;

  const allowed = await limiter.check(auth.user.id);
  if (!allowed) {
    return NextResponse.json({ error: 'Too many requests' }, { status: 429 });
  }

  try {
    const body = await req.json();
    const { income, gestation, support, region } = body as Record<string, string | undefined>;

    const sanitize = (v: string | undefined, max = 200) =>
      v ? v.slice(0, max).replace(/[<>"'`;${}]/g, '') : undefined;

    const query = `I am a parent in ${sanitize(region) || 'New Zealand'}.
My household income is ${sanitize(income) || 'unknown'}.
My baby was born at ${sanitize(gestation) || 'unknown'} weeks gestation.
Currently I am receiving: ${sanitize(support) || 'nothing'}.
Please evaluate my eligibility for financial grants such as Best Start, WINZ, or Disability Allowance.`;

    const result = await agentGraph.invoke(
      {
        query,
        consentGiven: true,
        intent: 'EXECUTION',
        currentAgent: 'funding_eligibility_checker',
        messages: [new HumanMessage(query)],
      },
      {
        configurable: { thread_id: `financial_eval_${Date.now()}` },
      }
    );

    return NextResponse.json({ 
      success: true, 
      report: result.finalResponse,
      sources: result.sources || []
    });

  } catch (error: any) {
    // If we hit the interrupt due to human review (which funding_eligibility_checker requires)
    if (error && (error.name === 'Interrupt' || error.name === 'GraphInterrupt')) {
      const interruptValue = error.value || error.interrupt || {};
      return NextResponse.json({ 
        success: true, 
        report: interruptValue.proposedResponse,
        note: 'This report was generated by AI and is pending human review by a financial counselor.'
      });
    }

    return NextResponse.json({ error: 'Internal Server Error' }, { status: 500 });
  }
}
